server {
    listen 80;
    server_name localhost;

    # Rotas Padrões SPA (O que quebrar viaja pro index)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # PROXY PARA API DO BACKEND (Autenticação e outros endpoints)
    location /api/ {
        proxy_pass http://rust-collector:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # PROXY PARA CLICKHOUSE API HTTP VIRTUAL
    # Usando DNS Hostname interno do Compose ('clickhouse')
    location /ch-api/ {
        # Oculta a credencial do administrador para o ClickHouse não devolver 401
        proxy_set_header Authorization "";

        proxy_pass http://clickhouse:8123/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # PROXY PARA WEBSOCKET (Live Telemetry)
    location /ws {
        proxy_pass http://rust-collector:3000/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
